language: php

dist:- trusty

# list any PHP version you want to test against
php:
  - 7.0

# optionally specify a list of environments, for example to test different RDBMS
 #matrix:
 #- DEPENDENCIES="high"
 #- DEPENDENCIES="low"

# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  allow_failures:
    - php: 7.0
    - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
#before_script:
 #- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
 #- if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
 #- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: 
phpunit test.php
phpunit holamundo.php
#- sbt $TASKS
# configure notifications (email, IRC, campfire etc)
notifications:
email: - pruebatravis@outlook.com

    Contact GitHub API Training Shop Blog About 


